# Generated by Django 5.1.5 on 2025-01-14 16:36

import django.contrib.postgres.fields.hstore
import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Производитель')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Не менее 5 символов'), django.core.validators.MaxLengthValidator(255, message='Не более 255 символов')], verbose_name='Наименование')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True, verbose_name='Slug')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, default='default.webp', null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('num_in_stock', models.IntegerField(default=1, verbose_name='Количество')),
                ('params', django.contrib.postgres.fields.hstore.HStoreField(default=dict, verbose_name='Характеристики')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Комплектующие для ПК',
                'verbose_name_plural': 'Комплектующие для ПК',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='shop_hardwa_time_cr_0023b3_idx')],
            },
        ),
    ]
